services:
  backend:
    build: ./victim/backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - lab-net

  attacker:
    build: ./attacker
    container_name: attacker
    ports:
      - "1389:1389"
      - "8000:8000"
      - "4444:4444"
    networks:
      - lab-net

networks:
  lab-net:
